# Generated by Django 6.0.3 on 2026-04-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('azuracast_station_id', models.IntegerField(verbose_name='ID da Estação no AzuraCast')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Será preenchido automaticamente pelo YouTube se deixado em branco.', max_length=200)),
                ('youtube_url', models.URLField(verbose_name='Link do YouTube')),
                ('tipo', models.CharField(choices=[('MUSICA', 'Música (Toca em todas)'), ('ANUNCIO_GLOBAL', 'Anúncio Global (Toca em todas)'), ('ANUNCIO_LOCAL', 'Anúncio Local (Toca em selecionadas)')], default='MUSICA', max_length=20)),
                ('arquivo_mp3', models.FileField(blank=True, null=True, upload_to='audios_processados/')),
                ('enviado_azuracast', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('unidades', models.ManyToManyField(blank=True, help_text='Selecione as unidades APENAS se for um Anúncio Local.', to='gestao.unidade')),
            ],
        ),
    ]
